theme: jekyll-theme-minimal
title: Yuxin Hu
description: Incoming PhD Student @ UC Berkeley | Mechanical Engineer | Product Design
project1: Class Project - Sleep Aid Device
project2: Class Project - Algae Removal Device
project3: Class Project - Auto Parking Robot
project4: Class Project - Robotics Collection
project5: Class Project - The "Wellness" System
project6: Class Project - Transportation Challenge
project7: Class Project - Unity Games
project8: Class Project - MIPS CPU
project9: Hobby Project - Rhythm Game Robot
