theme: jekyll-theme-minimal
title: Yuxin Hu
description: Graduate Student @ UC Berkeley | Mechanical Engineer | Product Design
project1: Project - Sleep Tracking Band
project2: Project - Auto Parking Robot
project3: Project - The "Wellness" System
