theme: jekyll-theme-minimal
title: Yuxin Hu
description: Graduate Student @ UC Berkeley | Mechanical Engineer | Product Design
project1: Sleep Tracking Band
project2: Auto Parking Robot
project3: The "Wellness" System
