theme: jekyll-theme-minimal
title: Yuxin Hu
description: Graduate Student @ UC Berkeley | Mechanical Engineer | Product Design
project1: Project - Sleep Aid Device
project2: Project - Algal
project3: Project - Auto Parking Robot
project4: Project - The "Wellness" System
