theme: jekyll-theme-minimal
title: Yuxin Hu
description: Graduate Student @ UC Berkeley | Mechanical Engineer | Product Design
project1: Class Project - Sleep Aid Device
project2: Class Project - Algal
project3: Class Project - Auto Parking Robot
project4: Class Project - The "Wellness" System
project5: Hobby Project - Rhythm Game Bot
project6: Class Project - Unity Games (Playable online)
